version: '2'
services:
  mongo:
    image: mongo
    ports: ["27019:27017"]
    restart: "always"
    volumes:
      - signlab:/data/db
  signlab:
    image: hicsail/signlab:latest
    restart: always
    depends_on:
      - mongo
    ports: ["6001:3000"]
    env_file:
      - stack.env
volumes:
  signlab:
    external: true
