version: '2'
services:
  mongo:
    image: mongo
    ports: ["27017:27017"]
  signlab:
    build: .
    restart: always
    depends_on:
      - mongo
    ports: ["9000:9000"]
    environment:
      - NODE_ENV='local'
