version: '2'
services:
  mongo:
    image: mongo
    ports: ["27017:27017"]
    volumes:
      - ./db:/data/db
  signlab:
    build: .
    restart: always
    depends_on:
      - mongo
    ports: ["3000:3000"]
    environment:
      - NODE_ENV=docker
