version: '2'
services:
  mongo:
    image: mongo
    ports: ["27017:27017"]
    restart: "always"
    volumes:
      - signlab-staging:/data/db
  signlab:
    image: hicsail/signlab:unstable
    restart: always
    depends_on:
      - mongo
    ports: ["6000:3000"]
    env_file:
      - ../stack.env
volumes:
  signlab-staging:
    external: true
