version: '2'
services:
  mongo:
    image: mongo
    restart: "always"
    volumes:
      - signlab-staging:/data/db
  signlab:
    image: hicsail/signlab:unstable
    restart: always
    depends_on:
      - mongo
    ports: ["6000:3000"]
    env_file:
      - ../stack.env
  gateway:
    image: hicsail/signlab-gateway:unstable
    restart: always
    depends_on:
      - signlab
    ports: ["6001:3002"]
    env_file:
      - ../stack.env
  signlab-client:
    image: hicsail/signlab-client:unstable
    restart: always
    ports: ["6003:80"]
    env_file:
      - ../stack.env
volumes:
  signlab-staging:
    external: true
