version: '2'
services:
  mongo:
    image: mongo
    restart: "always"
    volumes:
      - signlab:/data/db
  signlab:
    image: hicsail/signlab:latest
    restart: always
    depends_on:
      - mongo
    ports: ["6001:3000"]
    env_file:
      - ../stack.env
  gateway:
    image: hicsail/signlab-gateway:latest
    restart: alawys
    depends_on:
      - signlab
    ports: ["6002:3000"]
volumes:
  signlab:
    external: true
