name: Setup for SignLab workflows

on:
  workflow_call:
    # Controls which tests are run, ideally the user would provide a list of
    # actions they want to take place, but as of writing this lists are not
    # supported.
    inputs:
      run-linting:
        type: boolean
        required: false
        default: true
      run-client-unit-tests:
        type: boolean
        required: false
        default: true
      run-server-unit-tests:
        type: boolean
        required: false
        default: true
      run-e2e-tests:
        type: boolean
        required: false
        default: true
      run-docker-build:
        type: boolean
        required: false
        default: false

jobs:
  base:
    runs-on: ubuntu-latest

    steps:
      # Checkout the respository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # Setup node
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: NPM Install
        run: npm install --only-dev

      # Run linting
      - name: Check for Linting Issues
        if: ${{ inputs.run-linting }}
        run: npm run lint


      # Running unit tests
      - name: Client Side Unit Tests
        if: ${{ inputs.run-client-unit-tests }}
        run: npm run test --workspace=client

      - name: Server Side Unit Tests
        if: ${{ inputs.run-server-unit-tests }}
        run: npm run test --workspace=server


      # Run e2e testing
      - name: Build Code
        if: ${{ inputs.run-e2e-tests }}
        run: |
          npm run build:prod
          mkdir -p server/bucket-test/Responses

      - name: Start MongoDB Instance
        if: ${{ inputs.run-e2e-tests }}
        uses: supercharge/mongodb-github-action@1.8.0

      - name: Run e2e testing
        uses: cypress-io/github-action@v4.2.0
        if: ${{ inputs.run-e2e-tests }}
        with:
          start: npm run start:ci
        env:
          MONGO_URI: mongodb://localhost:27017/signlab-test

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
