name: client
on:
  workflow_dispatch:
  push:
    paths:
      - 'client/**'
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - 'client/**'
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    name: Check for Linting Errors and Unit Test Errors
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: NPM Install
        run: npm install --force
        shell: bash

      - name: Build GraphQL Code
        run: npm run introspection

      - name: Check for Linting Issues
        run: npm run lint --workspace=client

      - name: Check for Prettier Issues
        run: npm run prettier --workspace=client

      - name: Run unit tests for the client
        run: npm run test --workspace=client

  docker-build:
    runs-on: ubuntu-latest
    name: Docker Build (and Deploy)
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Test Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: client/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: hicsail/signlab-client:unstable
          build-args: |
            PRODUCTION="false"
            GRAPHQL_ENDPOINT=${{ secrets.GRAPHQL_ENDPOINT }}
            ASL_LEX_ID=${{ secrets.ASL_LEX_ID }}
            BACKEND_URL=${{ secrets.BACKEND_URL }}

      - name: Build & Push Docker Production Build
        uses: docker/build-push-action@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          context: .
          file: client/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: hicsail/signlab-client:latest,hicsail/signlab-client:${{github.ref_name}}
          build-args: |
            PRODUCTION="true"
            GRAPHQL_ENDPOINT=${{ secrets.GRAPHQL_ENDPOINT_PRODUCTION }}
            ASL_LEX_ID=${{ secrets.ASL_LEX_ID_PRODUCTION }}
            BACKEND_URL=${{ secrets.BACKEND_URL_PRODUCTION }}

      - name: Push to Staging
        uses: fjogeleit/http-request-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          method: "POST"
          url: ${{ secrets.PORTAINER_WEBHOOK }}
          preventFailureOnNoResponse: true

      - name: Push to Production
        uses: fjogeleit/http-request-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          method: "POST"
          url: ${{ secrets.PORTAINER_WEBHOOK_PRODUCTION }}
          preventFailureOnNoResponse: true
