name: Release Actions

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build And Push to Docker Hub
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push SignLab
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: hicsail/signlab:${{github.ref_name}},hicsail/signlab:latest
          build-args: |
            PRODUCTION="true"
            GRAPHQL_ENDPOINT=${{ secrets.GRAPHQL_ENDPOINT_PRODUCTION }}
            ASL_LEX_ID=${{ secrets.ASL_LEX_ID_PRODUCTION }}

      - name: Build and push Gateway
        uses: docker/build-push-action@v3
        with:
          push: true
          file: gateway/Dockerfile
          tags: hicsail/signlab-gateway:${{github.ref_name}},hicsail/signlab-gateway:latest

      - name: Push to Prod
        uses: fjogeleit/http-request-action@v1
        with:
          method: 'POST'
          url: ${{ secrets.PORTAINER_WEBHOOK_PROD }}
          preventFailureOnNoResponse: true
